/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-07-07 09:12:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BillReport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("      <title>TNEB</title>\r\n");
      out.write("      <style>\r\n");
      out.write("\t     #container{\t\t\t\r\n");
      out.write("\t\t\tborder: 1px solid black; \r\n");
      out.write("\t\t\tborder-image: none; \r\n");
      out.write("\t\t\twidth: 55%; \r\n");
      out.write("\t\t\tmargin-top: 4%;\r\n");
      out.write("\t\t\t margin-left: 16%;\r\n");
      out.write("\t\t }\r\n");
      out.write("         #header {\r\n");
      out.write("         background-color:cadetBlue;\r\n");
      out.write("         color:white;\r\n");
      out.write("         text-align:center;\r\n");
      out.write("         padding:5px;\r\n");
      out.write("         }\r\n");
      out.write("         #nav {\r\n");
      out.write("         line-height:30px;\r\n");
      out.write("         background-color:silver;\r\n");
      out.write("         height:300px;\r\n");
      out.write("         width:100px;\r\n");
      out.write("         float:left;\r\n");
      out.write("         padding:5px;\t      \r\n");
      out.write("         }\r\n");
      out.write("         #section {\r\n");
      out.write("         width:350px;\r\n");
      out.write("         float:left;\r\n");
      out.write("         padding:10px;\t \t\r\n");
      out.write("\t\t  margin-top: 9%;\r\n");
      out.write("\t\t  margin-left: 20%;\t\r\n");
      out.write("         }\r\n");
      out.write("         #footer {\r\n");
      out.write("         background-color:grey;\r\n");
      out.write("         color:white;\r\n");
      out.write("         clear:both;\r\n");
      out.write("         text-align:center;\r\n");
      out.write("         padding:5px;\t \t \r\n");
      out.write("         }\r\n");
      out.write("         #info{\r\n");
      out.write("         width: 87%; \r\n");
      out.write("         margin-top: 8%;\r\n");
      out.write("         float: left;\r\n");
      out.write("         }\r\n");
      out.write("      </style>\r\n");
      out.write("   </head>\r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("   function myfunction(){\t   \r\n");
      out.write("\t    var divHtml = '<div>Customer Name : <input type=\"text\" placeholder=\"Full Name\" name=\"custName\"></div>';\r\n");
      out.write("\t    \tdivHtml = divHtml+''\r\n");
      out.write("\t        divHtml = divHtml+ '<div>Customer Id : <input type=\"text\" placeholder=\"customerId\" name=\"newCustId\" style=\"margin-left: 7%;\"></div>';\r\n");
      out.write("\t\t\tdivHtml = divHtml+ '<div>Address : <input type=\"text\" placeholder=\"Full Address\" name=\"address\" style=\"margin-left: 14.75%;\">'; \r\n");
      out.write("\t\t\tdivHtml = divHtml+ '<input type=\"submit\" name=\"insertCust\" value=\"Insert\"></div>'; \r\n");
      out.write("\t     $('#section').html(divHtml);\r\n");
      out.write("\t   }\r\n");
      out.write("   function myReportfun(){   \r\n");
      out.write("\t   var divhtml = 'Search Customer : <input type=\"text\" value=\"\"  name=\"report\" />';\r\n");
      out.write("\t\t\t   divhtml = divhtml+'<input type=\"submit\" value=\"Submit\" />';\r\n");
      out.write("\t\t\t\tdivhtml = divhtml+'<input type=\"submit\" value=\"Generate All Reports\" name=\"report\" style=\"margin-top: 11%; margin-left: 30%;\" />';\r\n");
      out.write("\t\t$('#section').html(divhtml);\r\n");
      out.write("   }\r\n");
      out.write("   function hadoopSearch(){\r\n");
      out.write("\t   var divhtml='Search Customer : <input type=\"text\" value=\"\"  name=\"hadoopId\" />';\r\n");
      out.write("\t   divhtml = divhtml+'<input type=\"submit\" value=\"Submit\" name=\"hadoopSearch\" />';\r\n");
      out.write("\t   divhtml = divhtml+' <input type=\"submit\" value=\"Generate Hadoop Reports\" name=\"hadoop\" style=\"margin-top: 11%; margin-left: 30%;\" />';\r\n");
      out.write("\t   $('#section').html('');\r\n");
      out.write("\t   $('#section').html(divhtml);\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("   <body>\r\n");
      out.write("      <form action=\"serv/bill\" method=\"post\">\r\n");
      out.write("\t  <div id=\"container\">\r\n");
      out.write("         <div id=\"header\">\r\n");
      out.write("\t\t\t<img src=\"C:\\Users\\Administrator\\Desktop\\tneblogo.jpg\" style=\"width: 114px; height: 87px; margin-top: -4px; margin-left: -5px; float: left;\"/>\r\n");
      out.write("            <h1>TNEB</h1>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"nav\">\r\n");
      out.write("            <input type=\"button\" value=\"Add Customer\" onclick=\"myfunction();\" style=\"width:100%;margin-top: 130%;\">\r\n");
      out.write("            <input type=\"button\" value=\"Report\" onclick=\"myReportfun();\" style=\"width:100%; margin-top: 10%;\">\r\n");
      out.write("            <input type=\"button\" value=\"Hadoop\" onclick=\"hadoopSearch();\" style=\"width:100%; margin-top: 10%;\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"section\">\r\n");
      out.write("             Search Customer : <input type=\"text\" value=\"\"  name=\"custId\" />\r\n");
      out.write(" \t         <input type=\"submit\" value=\"Submit\" />\r\n");
      out.write("  \t         <input type=\"submit\" value=\"Generate All Reports\" name=\"report\" style=\"margin-top: 11%; margin-left: 30%;\" />\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"info\"><marquee direction=\"right\" style=\"color:red;\">*Quotes of the day :\"If you don't wanna pay it save it...\"</marquee></div>\r\n");
      out.write("         <div id=\"footer\">\r\n");
      out.write("           Copyright © 2013.  TamilNadu Generation and Distribution Corporation Limited \r\n");
      out.write("         </div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("      </form>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
